{% set name = "tiler" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiler-{{ version }}.tar.gz
  sha256: ba570bd18c64ccc54b7cdc9fd42caf619c545acb6ecd85ea01d1b085c5759d1d
  patches:
    - exclude_tests.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - numpy
    - python >=3.6
    - tqdm

test:
  imports:
    - tiler
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/the-lay/tiler
  summary: N-dimensional NumPy array tiling and merging with overlapping, padding and tapering
  dev_url: https://github.com/the-lay/tiler
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - goanpeca
    - the-lay
